FROM ubuntu:18.04

RUN true \
  && apt-get update \
  && DEBIAN_FRONTEND=noninteractive apt-get upgrade --yes \
  && DEBIAN_FRONTEND=noninteractive apt-get install \
    --no-install-recommends --yes \
    # discovered with apt-get build-dep:
    build-essential \
    debhelper \
    autoconf \
    libtool \
    automake \
    chrpath \
    libreadline-dev \
    tcl8.6-dev \
    # for cloning over https with git:
    git ca-certificates \
    # for /usr/bin/tclsh:
    # (tcl8.6-dev brings in tcl8.6 which only includes tclsh8.6)
    tcl \
  && rm -rf /var/lib/apt/lists/* \
