FROM fedora:31

RUN true \
  && dnf --assumeyes upgrade \
  && dnf install --assumeyes \
    git make gcc ncurses-devel readline-devel glibc-devel autoconf tcl-devel \
  && dnf clean all \
  && rm -rf /var/cache/yum \

#
# Copyright 2020 Keith Maxwell
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# /lumosql-build/fedora/Containerfile
