FROM gentoo/portage AS portage

FROM gentoo/stage3-amd64
COPY --from=portage /var/db/repos/gentoo /var/db/repos/gentoo
RUN true \
  && emerge -v --update world \
  && emerge -v dev-lang/tcl dev-vcs/git \
  && rm -r /var/db/repos /var/cache/distfiles /var/log \

#
# Copyright 2020 Keith Maxwell
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# /lumosql-build/gentoo/Containerfile
