on: { push: { branches: [master, staging, trying] } }

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and push
    env: { CONTAINER_REPO: quay.io/keith_maxwell/lumosql-build }
    steps:
      - uses: actions/checkout@v2
      - name: Log into the container repository
        run: |
          docker login  \
            --username "${{ secrets.CONTAINER_REPO_USERNAME }}" \
            --password "${{ secrets.CONTAINER_REPO_TOKEN }}" \
            "${CONTAINER_REPO%%/*}"
      - name: Build all of the container images
        run: |
          for i in lumosql-build/* ; do
            docker build "$i" --file "$i/Containerfile" --tag "$i"
          done
      - name: Push the images
        if: github.ref == 'refs/heads/master'
        run: |
          for i in lumosql-build/* ; do
            name="$CONTAINER_REPO:${i##*/}"
            docker tag "$i" "$name"
            docker push "$name"
            name="$name-${{ github.sha }}"
            docker tag "$i" "$name"
            docker push "$name"
          done
