on: { push: { branches: [master, staging, trying] } }

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and push
    env:
      DOMAIN: docker.pkg.github.com
    steps:
      - uses: actions/checkout@v2
      - name: Log into registry
        run:
          docker login $DOMAIN --username ${{ github.actor }} --password "${{
          secrets.GITHUB_TOKEN }}"
      - name: Build the Debian container image
        run:
          docker build lumosql-debian --file lumosql-debian/Containerfile --tag
          lumosql-debian
      - name: Push image
        if: github.ref == 'refs/heads/master'
        env:
          REPO: ${{ env.DOMAIN }}/${{ github.repository }}
        run: |
          docker tag lumosql-debian "$REPO/lumosql-debian:${{ github.sha }}"
          docker tag lumosql-debian "$REPO/lumosql-debian:latest"
          docker push "$REPO/lumosql-debian:${{ github.sha }}"
          docker push "$REPO/lumosql-debian:latest"
