on: { push: { branches: [master, staging, trying] } }

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and push
    env: { DOMAIN: docker.pkg.github.com }
    steps:
      - uses: actions/checkout@v2
      - name: Log into registry
        run:
          docker login $DOMAIN --username ${{ github.actor }} --password "${{
          secrets.GITHUB_TOKEN }}"
      - name: Build all of the container images
        run: |
          for i in lumosql-* ; do
            docker build "$i" --file "$i/Containerfile" --tag "$i"
          done
      - name: Push the images
        if: github.ref == 'refs/heads/master'
        env: { REPO: "${{ env.DOMAIN }}/${{ github.repository }}" }
        run: |
          for i in lumosql-* ; do
            docker tag "$i" "$REPO/$i:${{ github.sha }}"
            docker tag "$i" "$REPO/$i:latest"
            docker push "$REPO/$i:${{ github.sha }}"
            docker push "$REPO/$i:latest"
          done
